name: "Publish Firefox Extension"
on:
  push:
    tags:
      - "*"

jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Dependencies"
        run: yarn

      - name: "WXT Build"
        run: yarn build:firefox
        env:
          VITE_SHERPA_ROMEO_API_KEY: ${{ secrets.VITE_SHERPA_ROMEO_API_KEY }}

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .output/firefox-mv2

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign

      - name: Get last tag
        id: lasttag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Read Changelog
        id: changelog
        run: echo "::set-output name=body::$(git diff ${{ steps.lasttag.outputs.tag }} HEAD -- Changelog.md)"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./*.xpi,./*.zip"
          token: ${{ secrets.REPO_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
